source 'https://rubygems.org'

gem 'sinatra', '2.0.5'
gem 'haml', '5.0.4'
gem 'nokogiri', '1.10.1'
gem 'data_mapper', '1.2.0'
gem 'bcrypt', '3.1.12'
gem 'dm-sqlite-adapter', '1.2.0'
gem 'thin', '1.7.2'