version: "2.4"

services:
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    cpus: 1
    restart: always

  beenpwned:
    build: .
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    volumes:
      - ./:/app
    restart: always
    pids_limit: 50
    ulimits:
      nproc: 50
    mem_limit: 512m
