version: "2.4"

services:
  kv8:
    build: .
    ports:
      - 4242:4242
    volumes:
      - ./data:/app/data
    restart: always
    pids_limit: 50
    ulimits:
      nproc: 50
    mem_limit: 512m
