version: "2.4"

services:
  redis:
    image: redis:alpine
    volumes:
      - ./data:/data
    command: redis-server --appendonly yes
    restart: always

  pokupaika:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - redis
    restart: always
    environment:
      - NODE_ENV=production
    pids_limit: 50
    ulimits:
      nproc: 50
    mem_limit: 512m
