version: "3.2"

services:
  redis:
    image: redis:alpine
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    restart: always

  pokupaika:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - redis
    restart: always
